name: Build container images

on:
  push:
    paths-ignore:
        - "**.md"

jobs:

  build:

    runs-on: ubuntu-latest
    env: 
      PUBLISH: ${{ github.ref == 'refs/heads/main' }}
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker-compose build
    - name: DockerHub login
      if: ${{ env.PUBLISH }}
      run: echo ${{secrets.DOCKERHUB_TOKEN}} | docker login -u ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
    - name: Push the images
      if: ${{ env.PUBLISH }}
      run: docker-compose push
